### PR TITLE
Support unicorn 5 on Ubuntu Xenial

### PR DESCRIPTION
**Pull request by nhinds**
Fixes:
- Don't call `worker.tmp` if the method doesn't exist
- Don't try to access a global variable that doesn't exist on failures
- Run `systemctl enable <service>` before the `service` resource to work around PUP-4605 on systems with systemd (ubuntu xenial)
- Remove duplicate dependency on `ploperations/rack` in `Modulefile`

### CODE REVIEW

**Comment by danielparks** [comment]
Would you mind checking if changes I've committed to production fix the problems your running into? They include systemd support.

(They don't remove the duplicate dependency on `ploperations/rack` in the `Modulefile`.)

Thanks!

**Comment by nhinds** [comment]
Taking a quick look, no they will not fix the problem. You are accessing `$facts['service_provider']` to determine the default system service provider and performing different operations based on this.

1. The global `$facts` variable is [disabled by default prior to Puppet 4](https://docs.puppet.com/puppet/latest/reference/lang_facts_and_builtin_vars.html#the-factsfactname-hash), so this would just fail with an error in my version of Puppet (3.8.7 on the puppet master, 3.8.5 on the puppet agents)
2. The `service_provider` fact does not return `"systemd"` for Ubuntu 16.04 and Puppet 3.8.5, it returns `"debian"`.

My PR has the downside that it does not migrate the service to a `systemd` service, but since it detected the presence of systemd at runtime, it avoided running into these issues in Puppet's broken detection.

I can confirm that a quick puppet run with the current `master` (90825e1fe822cc7876fd9c9320439dde99addd35) simply fails with the message "Error: Could not retrieve catalog from remote server: Error 400 on SERVER: facts is not a hash or array when accessing it with service_provider at /etc/puppet/environments/production/modules/unicorn/manifests/app.pp:62 on node agent"

Setting `trusted_node_data = true` on my puppet master and retrying has the following result:
```
==> agent: Notice: /Stage[main]/.../Unicorn::App[my-app]/File[/etc/default/unicorn_my-app]/ensure: defined content as '{md5}75f3aab9e6e2e24decdbf16691c7a972'
==> agent: Info: /Stage[main]/.../Unicorn::App[my-app]/File[/etc/default/unicorn_my-app]: Scheduling refresh of Service[unicorn_my-app]
==> agent: Notice: /Stage[main]/.../Unicorn::App[my-app]/File[/opt/my-app/config/unicorn.config.rb]/ensure: defined content as '{md5}ed11ae79fc154a6c477f0469812976d3'
==> agent: Info: /Stage[main]/.../Unicorn::App[my-app]/File[/opt/my-app/config/unicorn.config.rb]: Scheduling refresh of Service[unicorn_my-app]
==> agent: Notice: /Stage[main]/.../Unicorn::App[my-app]/File[/etc/init.d/unicorn_my-app]/ensure: defined content as '{md5}15e9ae46b4fb9aed2303005ccafa3a84'
==> agent: Info: /Stage[main]/.../Unicorn::App[my-app]/File[/etc/init.d/unicorn_my-app]: Scheduling refresh of Service[unicorn_my-app]
==> agent: Error: Could not start Service[unicorn_my-app]: Execution of '/etc/init.d/unicorn_my-app start' returned 5: Starting unicorn_my-app (via systemctl): unicorn_my-app.serviceFailed to start unicorn_my-app.service: Unit unicorn_my-app.service not found.
==> agent:  failed!
==> agent: Error: /Stage[main]/.../Unicorn::App[my-app]/Service[unicorn_my-app]/ensure: change from stopped to running failed: Could not start Service[unicorn_my-app]: Execution of '/etc/init.d/unicorn_my-app start' returned 5: Starting unicorn_my-app (via systemctl): unicorn_my-app.serviceFailed to start unicorn_my-app.service: Unit unicorn_my-app.service not found.
==> agent:  failed!
==> agent: Notice: /Stage[main]/.../Unicorn::App[my-app]/Service[unicorn_my-app]: Triggered 'refresh' from 4 events
```

You can see that the puppet module is still managing the `/etc/init.d/unicorn_...` service (not the `systemd` service), and that attempting to start it runs into [PUP-4605](https://tickets.puppetlabs.com/browse/PUP-4605)

**Comment by danielparks** [comment]
Thanks for the detailed feedback. Sounds like I (or you) can work around that stuff.

**Comment by yachub** [comment]
Hello, it seems this PR has fallen through the cracks. If this is still a feature that you would like implemented, please open a new request at https://github.com/ploperations/ploperations-unicorn, as this repo has been migrated to another organization and the old one is being archived.

Respectfully,
Jake

**Pull request closed without merging**
