### PR TITLE
(PF-1605) Add Unicorn reload action to templated systemd unit

### PR DESCRIPTION
**Pull request by scotje**
Adds support for Unicorn's SIGUSR2 based 0-downtime restart action, implemented as a "reload" for systemctl.

### CODE REVIEW

**Comment by scotje** [comment]
Tested on forgenext-app01-dev:

```
root@forgenext-app01-dev:~# pb pf1605_add_reload_to_unicorn
Info: Using configured environment 'pf1605_add_reload_to_unicorn'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for i-0e0b6809f4ad99b1b
Info: Applying configuration version 'pe-compiler1-prod.ops.puppetlabs.net-pf1605_add_reload_to_unicorn-3aed9dc1e27'
Notice: /Stage[main]/Profile::Motd/Concat[/etc/motd]/File[/etc/motd]/content:
--- /etc/motd   2018-05-08 17:15:44.567947805 -0700
+++ /tmp/puppet-file20180509-11806-1ct4yw3      2018-05-09 11:00:59.197697412 -0700
@@ -9,7 +9,7 @@
 Debian 8.7/jessie amd64
 Processor: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz   Memory: 3.87 GiB

-       Puppet: 5.5.1 in production
+       Puppet: 5.5.1 in pf1605_add_reload_to_unicorn
        Facter: 3.11.1

          Ruby: 2.4.4

Info: Computing checksum on file /etc/motd
Info: /Stage[main]/Profile::Motd/Concat[/etc/motd]/File[/etc/motd]: Filebucketed /etc/motd to puppet with sum 0ed0c92d0e64195d7154602911f1e45c
Notice: /Stage[main]/Profile::Motd/Concat[/etc/motd]/File[/etc/motd]/content: content changed '{md5}0ed0c92d0e64195d7154602911f1e45c' to '{md5}dea73fd1e7940f5c9cdab964d483aa5a'
Notice: /Stage[main]/Profile::Base::Puppet/Ini_setting[pe-agent-environment]/value: value changed production to pf1605_add_reload_to_unicorn
Notice: /Stage[main]/Ruby/Package[rubygems]/ensure: created
Notice: /Stage[main]/Profile::Forgenext::Api/Unicorn::App[forge-api]/File[/etc/systemd/system/unicorn_forge-api.service]/content:
--- /etc/systemd/system/unicorn_forge-api.service       2018-05-08 17:16:02.655883572 -0700
+++ /tmp/puppet-file20180509-11806-1dghobi      2018-05-09 11:01:18.785630559 -0700
@@ -19,6 +19,7 @@
 Environment="NEWRELIC_AGENT_ENABLED=false"

 ExecStart=/usr/local/rbenv/shims/ruby ./bin/unicorn --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb
+ExecReload=/bin/kill -s USR2 $MAINPID
 KillSignal=SIGQUIT

 [Install]

Info: Computing checksum on file /etc/systemd/system/unicorn_forge-api.service
Info: /Stage[main]/Profile::Forgenext::Api/Unicorn::App[forge-api]/File[/etc/systemd/system/unicorn_forge-api.service]: Filebucketed /etc/systemd/system/unicorn_forge-api.service to puppet with sum 20d25080fd566bd04d22e850c457d637
Notice: /Stage[main]/Profile::Forgenext::Api/Unicorn::App[forge-api]/File[/etc/systemd/system/unicorn_forge-api.service]/content: content changed '{md5}20d25080fd566bd04d22e850c457d637' to '{md5}c0eaa19ea394fff933db387493de39d2'
Info: /Stage[main]/Profile::Forgenext::Api/Unicorn::App[forge-api]/File[/etc/systemd/system/unicorn_forge-api.service]: Scheduling refresh of Class[Systemd::Systemctl::Daemon_reload]
Notice: /Stage[main]/Profile::Forgenext::Web/Unicorn::App[forge-web]/File[/etc/systemd/system/unicorn_forge-web.service]/content:
--- /etc/systemd/system/unicorn_forge-web.service       2018-05-08 17:16:04.447877209 -0700
+++ /tmp/puppet-file20180509-11806-xl37bd       2018-05-09 11:01:18.801630505 -0700
@@ -18,6 +18,7 @@
 Environment="HONEYBADGER_REPORT_DATA=false"

 ExecStart=/usr/local/rbenv/shims/ruby ./bin/unicorn --daemonize --env main --config-file /opt/forge-web/config/forge-unicorn.rb
+ExecReload=/bin/kill -s USR2 $MAINPID
 KillSignal=SIGQUIT

 [Install]

Info: Computing checksum on file /etc/systemd/system/unicorn_forge-web.service
Info: /Stage[main]/Profile::Forgenext::Web/Unicorn::App[forge-web]/File[/etc/systemd/system/unicorn_forge-web.service]: Filebucketed /etc/systemd/system/unicorn_forge-web.service to puppet with sum 4849f3d740291257a178fdc8b2f7aea6
Notice: /Stage[main]/Profile::Forgenext::Web/Unicorn::App[forge-web]/File[/etc/systemd/system/unicorn_forge-web.service]/content: content changed '{md5}4849f3d740291257a178fdc8b2f7aea6' to '{md5}9967422e03c50a1989d8f4d05d4077bb'
Info: /Stage[main]/Profile::Forgenext::Web/Unicorn::App[forge-web]/File[/etc/systemd/system/unicorn_forge-web.service]: Scheduling refresh of Class[Systemd::Systemctl::Daemon_reload]
Info: Class[Systemd::Systemctl::Daemon_reload]: Scheduling refresh of Exec[systemctl-daemon-reload]
Notice: /Stage[main]/Systemd::Systemctl::Daemon_reload/Exec[systemctl-daemon-reload]: Triggered 'refresh' from 1 event
Info: Class[Systemd::Systemctl::Daemon_reload]: Scheduling refresh of Service[unicorn_forge-api]
Info: Class[Systemd::Systemctl::Daemon_reload]: Scheduling refresh of Service[unicorn_forge-web]
Notice: /Stage[main]/Profile::Forgenext::Api/Unicorn::App[forge-api]/Service[unicorn_forge-api]: Triggered 'refresh' from 1 event
Notice: /Stage[main]/Profile::Forgenext::Web/Unicorn::App[forge-web]/Service[unicorn_forge-web]: Triggered 'refresh' from 1 event
Notice: Applied catalog in 27.35 seconds
```

```
root@forgenext-app01-dev:~# systemctl status unicorn_forge-api.service
● unicorn_forge-api.service - Unicorn for forge-api
   Loaded: loaded (/etc/systemd/system/unicorn_forge-api.service; enabled)
   Active: active (running) since Wed 2018-05-09 11:01:20 PDT; 1min 15s ago
  Process: 14146 ExecStart=/usr/local/rbenv/shims/ruby ./bin/unicorn --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb (code=exited, status=0/SUCCESS)
 Main PID: 14185 (ruby)
   CGroup: /system.slice/unicorn_forge-api.service
           ├─14185 unicorn master --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb
           ├─14193 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[00]:    58 reqs,  1.0 req/s,   20ms avg,   2.0% util
           ├─14196 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[01]:    19 reqs,  0.4 req/s,   46ms avg,   1.6% util
           ├─14199 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[02]:    90 reqs,  1.2 req/s,   18ms avg,   2.3% util
           └─14206 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[03]:    55 reqs,  0.8 req/s,   34ms avg,   2.7% util

May 09 11:01:20 forgenext-app01-dev systemd[1]: Started Unicorn for forge-api.

root@forgenext-app01-dev:~# systemctl reload-or-restart unicorn_forge-api.service

root@forgenext-app01-dev:~# systemctl status unicorn_forge-api.service
● unicorn_forge-api.service - Unicorn for forge-api
   Loaded: loaded (/etc/systemd/system/unicorn_forge-api.service; enabled)
   Active: active (running) since Wed 2018-05-09 11:01:20 PDT; 1min 36s ago
  Process: 15210 ExecReload=/bin/kill -s USR2 $MAINPID (code=exited, status=0/SUCCESS)
  Process: 14146 ExecStart=/usr/local/rbenv/shims/ruby ./bin/unicorn --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb (code=exited, status=0/SUCCESS)
 Main PID: 15212 (ruby)
   CGroup: /system.slice/unicorn_forge-api.service
           ├─15212 unicorn master --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb
           ├─15248 unicorn worker[0] --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb
           ├─15250 unicorn worker[1] --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb
           ├─15256 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[02]:     4 reqs,  5.9 req/s,   70ms avg,  41.6% util
           └─15263 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[03]:     1 reqs,  3.8 req/s,  260ms avg, 100.0% util

May 09 11:01:20 forgenext-app01-dev systemd[1]: Started Unicorn for forge-api.
May 09 11:02:54 forgenext-app01-dev systemd[1]: Reloading Unicorn for forge-api.
May 09 11:02:54 forgenext-app01-dev systemd[1]: PID file /var/lib/forgeapi/unicorn.pid not readable (yet?) after reload.
May 09 11:02:54 forgenext-app01-dev systemd[1]: Reloaded Unicorn for forge-api.

root@forgenext-app01-dev:~# systemctl reload-or-restart unicorn_forge-api.service

root@forgenext-app01-dev:~# systemctl status unicorn_forge-api.service
● unicorn_forge-api.service - Unicorn for forge-api
   Loaded: loaded (/etc/systemd/system/unicorn_forge-api.service; enabled)
   Active: active (running) since Wed 2018-05-09 11:01:20 PDT; 2min 35s ago
  Process: 15801 ExecReload=/bin/kill -s USR2 $MAINPID (code=exited, status=0/SUCCESS)
  Process: 14146 ExecStart=/usr/local/rbenv/shims/ruby ./bin/unicorn --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb (code=exited, status=0/SUCCESS)
 Main PID: 15803 (ruby)
   CGroup: /system.slice/unicorn_forge-api.service
           ├─15803 unicorn master --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb
           ├─15834 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[00]:     2 reqs,  6.4 req/s,  130ms avg,  84.0% util
           ├─15836 unicorn forgenextapi.puppetlabs.com[bfcee4f] worker[01]:     1 reqs,  3.4 req/s,  297ms avg, 100.0% util
           ├─15841 unicorn worker[2] --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb
           └─15843 unicorn worker[3] --daemonize --env main --config-file /opt/forge-api/config/forge-unicorn.rb

May 09 11:01:20 forgenext-app01-dev systemd[1]: Started Unicorn for forge-api.
May 09 11:02:54 forgenext-app01-dev systemd[1]: Reloading Unicorn for forge-api.
May 09 11:02:54 forgenext-app01-dev systemd[1]: PID file /var/lib/forgeapi/unicorn.pid not readable (yet?) after reload.
May 09 11:02:54 forgenext-app01-dev systemd[1]: Reloaded Unicorn for forge-api.
May 09 11:03:53 forgenext-app01-dev systemd[1]: Reloading Unicorn for forge-api.
May 09 11:03:53 forgenext-app01-dev systemd[1]: PID file /var/lib/forgeapi/unicorn.pid not readable (yet?) after reload.
May 09 11:03:53 forgenext-app01-dev systemd[1]: Reloaded Unicorn for forge-api.
```

**Comment by scotje** [comment]
Future improvement might be to parameterize the signal used to restart since everyone might not implement USR2+QUIT.

**Comment by scotje** [comment]
@danielparks could you review this or suggest another reviewer? Heath will be looking at it also during his Thursday working time.

**Comment by scotje** [comment]
@danielparks I don't have write permissions on this repo, would you mind merging when you get a chance?

**Comment by danielparks** [comment]
Oh, sorry. I was in puppetlabs-modules mode waiting for a second +1.

**Pull request merged**
